### PR TITLE
Update footer

### PR DESCRIPTION
**Pull request by MinIsMin**
See https://github.com/supertuxkart/stk-code/issues/4080

Changed:
- Made links HTTPS
- Changed Addons link from http://addons.stk.net (server offline) to https://online.stk.net
- Updated copyright year (or `20XX - 2019`?)

### CODE REVIEW

**Comment by konstin** [comment]
Thank you!

**Comment by konstin** [comment]
It seems that the deploy service is still running but either the changes haven't been deployed or we need to restart some service to clear the caches. @vampy could you have a look please?

**Comment by MinIsMin** [comment]
Any update on this?

**Comment by MinIsMin** [comment]
Still not on main site.
Could the footer be updated before the 1.1 release?

**Comment by konstin** [comment]
I'm not managing the server anymore; You'll need to talk to STK's new maintainer.

I'll archive this repo since I have intention of updating it further.

**Pull request merged**
